In [1]:
with open("ProblemSolutionPythonV3.csv", "r", encoding="utf-8") as f:
    text = f.read()

In [2]:
print("Length of the dataset in characters: ",len(text))

Length of the dataset in characters:  1885296


In [3]:
print(text[:1000])

,Problem,Python Code
0,Write a NumPy program to repeat elements of an array. ,"import numpy as np
x = np.repeat(3, 4)
print(x)
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))
"
1,Write a Python function to create and print a list where the values are square of numbers between 1 and 30 (both included). ,"def printValues():
	l = list()
	for i in range(1,31):
		l.append(i**2)
	print(l)
		
printValues()
"
2,Write a Python program to remove duplicates from a list of lists. ,"import itertools
num = [[10, 20], [40], [30, 56, 25], [10, 20], [33], [40]]
print(""Original List"", num)
num.sort()
new_num = list(num for num,_ in itertools.groupby(num))
print(""New List"", new_num)
"
3,Write a NumPy program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib. ,"import numpy as np
import matplotlib.pyplot as plt
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.2)
y = np.sin(x)
print(""Plot the points using mat

In [4]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡«­°³»Âï–‘’“”…⊗╳꞉
115


In [5]:
with open("vocab.txt", "w", encoding="utf-8") as f:
    f.write("".join(chars))

In [6]:
# Define character mappings
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }

# Encoding and decoding functions
encode = lambda s: [stoi[c] for c in s]  # str -> list of ints
decode = lambda l: ''.join([itos[i] for i in l])  # list of ints -> str

# Use a string that matches your dataset characters
test_str = "def function_0():\n    return 42"

# Safe test
print(encode(test_str))
print(decode(encode(test_str)))


[70, 71, 72, 2, 72, 87, 80, 69, 86, 75, 81, 80, 65, 18, 10, 11, 28, 1, 2, 2, 2, 2, 84, 71, 86, 87, 84, 80, 2, 22, 20]
def function_0():
    return 42


In [7]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1885296]) torch.int64
tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91, 86, 74, 81, 80,  2, 37, 81,
        70, 71,  1, 18, 14, 57, 84, 75, 86, 71,  2, 67,  2, 48, 87, 79, 50, 91,
         2, 82, 84, 81, 73, 84, 67, 79,  2, 86, 81,  2, 84, 71, 82, 71, 67, 86,
         2, 71, 78, 71, 79, 71, 80, 86, 85,  2, 81, 72,  2, 67, 80,  2, 67, 84,
        84, 67, 91, 16,  2, 14,  4, 75, 79, 82, 81, 84, 86,  2, 80, 87, 79, 82,
        91,  2, 67, 85,  2, 80, 82,  1, 90,  2, 31,  2, 80, 82, 16, 84, 71, 82,
        71, 67, 86, 10, 21, 14,  2, 22, 11,  1, 82, 84, 75, 80, 86, 10, 90, 11,
         1, 90,  2, 31,  2, 80, 82, 16, 67, 84, 84, 67, 91, 10, 61, 61, 19, 14,
        20, 63, 14, 61, 21, 14, 22, 63, 63, 11,  1, 82, 84, 75, 80, 86, 10, 80,
        82, 16, 84, 71, 82, 71, 67, 86, 10, 90, 14,  2, 20, 11, 11,  1,  4,  1,
        19, 14, 57, 84, 75, 86, 71,  2, 67,  2, 50, 91, 86, 74, 81, 80,  2, 72,
        87, 80, 69, 86, 75, 81, 80,  2, 86, 81,  2, 69, 84, 71, 67, 86, 71,  2,
      

In [8]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 16
train_data[:block_size+1]

tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91, 86, 74, 81, 80,  2, 37])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target =y[t]
  print(f"when input is {context} the target: {target}")

when input is tensor([14]) the target: 50
when input is tensor([14, 50]) the target: 84
when input is tensor([14, 50, 84]) the target: 81
when input is tensor([14, 50, 84, 81]) the target: 68
when input is tensor([14, 50, 84, 81, 68]) the target: 78
when input is tensor([14, 50, 84, 81, 68, 78]) the target: 71
when input is tensor([14, 50, 84, 81, 68, 78, 71]) the target: 79
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79]) the target: 14
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14]) the target: 50
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50]) the target: 91
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91]) the target: 86
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91, 86]) the target: 74
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91, 86, 74]) the target: 81
when input is tensor([14, 50, 84, 81, 68, 78, 71, 79, 14, 50, 91, 86, 74, 81]) the target: 80
when input is tensor([14, 50, 84, 81, 68, 78, 71

In [11]:
torch.manual_seed(1337)
batch_size = 8
block_size = 16

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([8, 16])
tensor([[ 4, 11,  1, 67,  2, 31,  2, 67, 84, 84, 81, 89, 16, 87, 86, 69],
        [67, 80, 73, 71, 80, 87, 79, 68, 71, 84, 28,  1, 97,  2, 97,  2],
        [75, 79, 67, 73, 71, 85, 11, 95,  4,  4, 11,  1, 97, 97,  1,  5],
        [82, 78, 75, 86,  2, 67,  2, 70, 67, 86, 67, 85, 71, 86,  2, 86],
        [82, 16, 81, 80, 71, 85, 10, 10, 19, 14, 20, 11, 14,  2, 70, 86],
        [74,  4,  4, 14,  1, 97, 97, 97,  4,  4, 53, 71, 69, 81, 80, 70],
        [75, 85, 86,  2, 75, 85,  2, 28,  2,  4,  4,  2, 13,  2, 85, 86],
        [73, 31, 85, 86, 84, 75, 80, 73, 16, 84, 71, 82, 78, 67, 69, 71]])
targets:
torch.Size([8, 16])
tensor([[11,  1, 67,  2, 31,  2, 67, 84, 84, 81, 89, 16, 87, 86, 69, 80],
        [80, 73, 71, 80, 87, 79, 68, 71, 84, 28,  1, 97,  2, 97,  2, 72],
        [79, 67, 73, 71, 85, 11, 95,  4,  4, 11,  1, 97, 97,  1,  5,  2],
        [78, 75, 86,  2, 67,  2, 70, 67, 86, 67, 85, 71, 86,  2, 86, 81],
        [16, 81, 80, 71, 85, 10, 10, 19, 14, 20, 11, 1

In [12]:
print(xb)

tensor([[ 4, 11,  1, 67,  2, 31,  2, 67, 84, 84, 81, 89, 16, 87, 86, 69],
        [67, 80, 73, 71, 80, 87, 79, 68, 71, 84, 28,  1, 97,  2, 97,  2],
        [75, 79, 67, 73, 71, 85, 11, 95,  4,  4, 11,  1, 97, 97,  1,  5],
        [82, 78, 75, 86,  2, 67,  2, 70, 67, 86, 67, 85, 71, 86,  2, 86],
        [82, 16, 81, 80, 71, 85, 10, 10, 19, 14, 20, 11, 14,  2, 70, 86],
        [74,  4,  4, 14,  1, 97, 97, 97,  4,  4, 53, 71, 69, 81, 80, 70],
        [75, 85, 86,  2, 75, 85,  2, 28,  2,  4,  4,  2, 13,  2, 85, 86],
        [73, 31, 85, 86, 84, 75, 80, 73, 16, 84, 71, 82, 78, 67, 69, 71]])


In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([128, 115])
tensor(5.2057, grad_fn=<NllLossBackward0>)
	E[B°oZ'­Â³u6(ZOHK8Wb«b{fWRz$TaXJ6fF$
6gy»”­_ mCDK0aP)P"0P[–hc9Z.$‘AJ0ZZ?eac°P#vcxZp¡’!V)ïQ;q0nWz+OWO


In [14]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [15]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.991772174835205


In [16]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	n>F< C)Q¡&6”<[?x{1MH’"VZ°0r‘mrI&꞉!}Ây%oBK@g(Â(Â^-xU¡U	V8«-#raO<=n 1³ N³x`POOH:z_@J
ï…³02(}z“Âm.8N»s ll %3“)0m.4=%<!,IG(‘x.\ {%\»qzh|8zfÂcw³2A«#L&Im:{-r	f8xsXaCLUJe*w³PfR­'g5‘JxZrnx«'ZHf db"K꞉;}ï“?U¡³Q {+XJn¡+8tOm»ÂU3kFZ9^¡q!s^([?xGï]
Nf«/»O	= x+2e(dBv@yK»P1–³A¡tvi1`wCC-1
#7…)S&-~ x⊗08qR#“{PfDE–…“n…eSj%1i7Z:$…꞉~<g@|w&(*7_ExZYC*WPyDTSj!4?He(.\B’O}9)\6*1o w,⊗P#G-~ {}}
dep>Epo[qW»=I7)^5d.~1:
dv3KGyu.oFclAW&T?x…‘Â1(2x	 eats lo‘ÂK4K	³{D<sI‘TH­sÂTd⊗NdTWdv^Mf8y}‘LKNRPyx)$KE%B
m1?HWaBl`w…)–V”h9”F<Z4ï5&7


In [17]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [18]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [19]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [20]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [21]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [22]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [23]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [24]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [25]:
k.var()

tensor(1.0449)

In [26]:
q.var()

tensor(1.0700)

In [27]:
wei.var()

tensor(1.0918)

In [28]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [30]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [31]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [32]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [33]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 8000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('ProblemSolutionPythonV3.csv', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.216179 M parameters
step 0: train loss 4.7847, val loss 4.7305
step 100: train loss 2.9032, val loss 2.8585
step 200: train loss 2.6825, val loss 2.6323
step 300: train loss 2.5451, val loss 2.5205
step 400: train loss 2.4552, val loss 2.4475
step 500: train loss 2.3609, val loss 2.3102
step 600: train loss 2.2620, val loss 2.2250
step 700: train loss 2.1659, val loss 2.1382
step 800: train loss 2.0812, val loss 2.0647
step 900: train loss 2.0548, val loss 1.9600
step 1000: train loss 1.9757, val loss 1.9033
step 1100: train loss 1.8980, val loss 1.8687
step 1200: train loss 1.8926, val loss 1.8148
step 1300: train loss 1.8315, val loss 1.7700
step 1400: train loss 1.8220, val loss 1.7653
step 1500: train loss 1.7890, val loss 1.7440
step 1600: train loss 1.7460, val loss 1.7340
step 1700: train loss 1.7217, val loss 1.6980
step 1800: train loss 1.7168, val loss 1.6694
step 1900: train loss 1.6907, val loss 1.6693
step 2000: train loss 1.6827, val loss 1.6408
step 2100: train loss 1.

In [34]:
def generate_from_prompt(prompt: str, max_new_tokens=200, device='cuda' if torch.cuda.is_available() else 'cpu'):
    model.eval()
    context = torch.tensor(encode(prompt), dtype=torch.long, device=device).unsqueeze(0)
    with torch.no_grad():
        generated = model.generate(context, max_new_tokens=max_new_tokens)
    return decode(generated[0].tolist())


In [36]:
prompt = "Write a NumPy program to repeat elements of an array."
output = generate_from_prompt(prompt)
print(output)

Write a NumPy program to repeat elements of an array.
     x = n [inth
    i = int(input(""Put.perecoding unique values data to sorted ls. ,""def items.max_number(str1=np.uses(21,3,5,30,190)
print(array_nums))
print(""\nApprode at a list of that between


In [37]:
prompt = "Write a Python function to create and print a list where the values are square of numbers"
print(generate_from_prompt(prompt))

Write a Python function to create and print a list where the values are square of numbers:"")
print(data) as np
average
print (""\rady 1cepated a duafe to modove a itle number with objecoding empty to list heade delim({}:keyNone:%11 < 2^0DC, 'k'))
print('Date_eexid uz (25):
          whil


In [ ]:
# Save model weights
torch.save(model.state_dict(), "codegpt_model.pt")